-- Initial database schema

CREATE TABLE pauta (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    descricao VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE sessao (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    pauta_id BIGINT NOT NULL REFERENCES pauta (id),
    inicio TIMESTAMP WITH TIME ZONE NOT NULL,
    fim TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(20) NOT NULL
);

CREATE TABLE associado (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    cpf VARCHAR(20) NOT NULL,
    CONSTRAINT uk_associado_cpf UNIQUE (cpf)
);

CREATE TABLE voto (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    sessao_id BIGINT NOT NULL REFERENCES sessao (id),
    associado_id BIGINT NOT NULL REFERENCES associado (id),
    opcao VARCHAR(10) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_voto_sessao_associado UNIQUE (sessao_id, associado_id)
);
